services:
  clickhouse:
    image: clickhouse/clickhouse-server:22.8
    ports:
      - "9000:9000"
      - "8123:8123"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  otel-collector:
    image: signoz/signoz-otel-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - clickhouse

  signoz:
    image: signoz/signoz:latest
    ports:
      - "8080:8080"
    environment:
      - SIGNOZ_TELEMETRYSTORE_PROVIDER=clickhouse
      - SIGNOZ_TELEMETRYSTORE_CLICKHOUSE_DSN=tcp://clickhouse:9000
      - SIGNOZ_ANALYTICS_ENABLED=true
    depends_on:
      - clickhouse
      - otel-collector
