receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  clickhousetraces:
    dsn: tcp://clickhouse:9000

  signozclickhousemetrics:
    dsn: tcp://clickhouse:9000

  clickhouselogsexporter:
    dsn: tcp://clickhouse:9000

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [clickhousetraces]
    metrics:
      receivers: [otlp]
      exporters: [signozclickhousemetrics]
    logs:
      receivers: [otlp]
      exporters: [clickhouselogsexporter]
